//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessorTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfessorTbl()
        {
            this.CourseTbls = new HashSet<CourseTbl>();
            this.DepartmentTbls = new HashSet<DepartmentTbl>();
            this.ExamTbls = new HashSet<ExamTbl>();
            this.Prof_Lecture_TBL = new HashSet<Prof_Lecture_TBL>();
            this.Prof_Video_TBL = new HashSet<Prof_Video_TBL>();
        }
    
        public int Prof_ID { get; set; }
        public string Prof_Name { get; set; }
        public string Prof_Email { get; set; }
        public string Prof_Pass { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public string Prof_Subject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTbl> CourseTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentTbl> DepartmentTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamTbl> ExamTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prof_Lecture_TBL> Prof_Lecture_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prof_Video_TBL> Prof_Video_TBL { get; set; }
    }
}
