//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartModel1 : DbContext
    {
        public SmartModel1()
            : base("name=SmartModel1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AdminTbl> AdminTbls { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CourseTbl> CourseTbls { get; set; }
        public virtual DbSet<DepartmentTbl> DepartmentTbls { get; set; }
        public virtual DbSet<EventTbl> EventTbls { get; set; }
        public virtual DbSet<Exam_Result_Tbl> Exam_Result_Tbl { get; set; }
        public virtual DbSet<ExamTbl> ExamTbls { get; set; }
        public virtual DbSet<MapTbl> MapTbls { get; set; }
        public virtual DbSet<NewsTbl> NewsTbls { get; set; }
        public virtual DbSet<ParkingTbl> ParkingTbls { get; set; }
        public virtual DbSet<Post_Reply_Tbl> Post_Reply_Tbl { get; set; }
        public virtual DbSet<PostTbl> PostTbls { get; set; }
        public virtual DbSet<Prof_Lecture_TBL> Prof_Lecture_TBL { get; set; }
        public virtual DbSet<Prof_Video_TBL> Prof_Video_TBL { get; set; }
        public virtual DbSet<ProfessorTbl> ProfessorTbls { get; set; }
        public virtual DbSet<QuestionsTbl> QuestionsTbls { get; set; }
        public virtual DbSet<StudentTbl> StudentTbls { get; set; }
    }
}
